spring:
  application:
    name: hana-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_container:3306/insurance?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlawjddn9704301@gmail.com
    password: emmw xrly mgyf revs
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework: WARN

server:
  forward-headers-strategy: native

#spring:
#  application:
#    name: hana-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://13.124.207.110:3306/insurance?serverTimezone=Asia/Seoul
#    username: root
#    password: root
#
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: true
#        use_sql_comments: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: rlawjddn9704301@gmail.com
#    password: emmw xrly mgyf revs
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
#          auth: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus, health, info
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#logging:
#  level:
#    root: INFO
#    org.springframework: WARN
#
#server:
#  forward-headers-strategy: native