name: hana-server workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Build
        run: ./gradlew build

      - name: Verify Build Output
        run: ls -la build/libs

      - name: Docker Image Build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build --no-cache --tag rlawjddn5980/hana-server:latest .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub Push
        run: docker push rlawjddn5980/hana-server:latest

      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ "$(sudo docker ps -q -f name=hana-server)" ]; then
              sudo docker stop hana-server || true
            fi
            if [ "$(sudo docker ps -a -q -f name=hana-server)" ]; then
              sudo docker rm hana-server || true
            fi
            sudo docker rmi rlawjddn5980/hana-server:latest --force || true
            sudo docker pull rlawjddn5980/hana-server:latest
            if [ ! "$(sudo docker network ls -q -f name=hana_network)" ]; then
              sudo docker network create hana_network
            fi
            sudo docker run -d -p 8080:8080 --name hana-server --network hana_network rlawjddn5980/hana-server:latest
